Sudo: required

Services:
    -docker
script:
    - docker build -t mannydesigns/node .
    - docker images mannydesigns/node 
before_deploy:
    - docker login -u "hem7246" -p "hemant3011"
deploy:
    provider: script
    script: docker push mannydesigns/node
    on:
        branch: master
