Sudo: required

Services:
    -docker
script:
    - docker build -t mannydesigns/node .
    - docker images mannydesigns/node 
before_deploy:
    - docker login -u hem7246 -p hemant3011
deploy:
    provider: script
    skip_cleanup: true
    script: docker push hem7246/mannydesigns/node
    on:
        branch: master
